Dataprovider considers webspace settings
trickreich/SuluArticleBundle pull request #5
Opened 2018-07-09 14:34 UTC by trickreich

2018-07-10 06:13 UTC, wachterjohannes requested changes

2018-07-10 06:13 UTC, wachterjohannes commented on Content/ArticleDataProvider.php
> +        if (array_key_exists('webspace', $propertyParameter)) {
are you sure that `webspace` and `webspaceKey` in options exists?

2018-07-10 06:13 UTC, wachterjohannes commented on Content/ArticleDataProvider.php
> +use ZendSearch\Lucene\Index\Term;
shouldnt be used in this class

2018-07-10 06:13 UTC, wachterjohannes commented on Document/Resolver/WebspaceResolver.php
> +            return null;
shouldnt be empty array?

2018-07-10 06:13 UTC, wachterjohannes commented on Tests/app/config/config.yml
> +    default_main_webspace: 'sulu_io'
add empty line

2018-07-10 06:13 UTC, wachterjohannes commented on Content/ArticleDataProvider.php
> +        if (array_key_exists('webspace', $propertyParameter)) {
as i can see in `vendor/sulu/sulu/src/Sulu/Component/SmartContent/ContentType.php` there is only `webspaceKey`.

2018-07-10 06:40 UTC, trickreich commented on Document/Resolver/WebspaceResolver.php
>          return $document->getAdditionalWebspaces() ? $document->getAdditionalWebspaces(): $this->defaultAdditionalWebspaces;
space

2018-07-11 10:38 UTC, wachterjohannes commented on Content/ArticleDataProvider.php
> +                return false;
`return null`

2018-07-11 11:17 UTC, merged